### PR TITLE
Fix/automated doc fixes

### PR DESCRIPTION
**Pull request by akmiller01**
Hi Amy,

If you could have a quick look through these for language (link text) that would be great. I've tested the HTML output and it seems fine. I've linked them all to 203 by default, but you might need to see if any need manually fixing to somewhere else.

### CODE REVIEW

**Comment by amy-silcock** [comment]
Hi @akmiller01, I'm working my way though them. I think the wagtail links need to start with 'https://iatistandard.org/'? Currently they start with /en ?

**Comment by amy-silcock** [comment]
The codelists linking to 2.03 are fine.

the element/attribute links we need to get linking to relevant version. E.g. 2.01 changelog should link to 2.01 elements.

**Comment by amy-silcock** [comment]
The versions we could do as find and replace for each file?

**Comment by akmiller01** [comment]
> Hi @akmiller01, I'm working my way though them. I think the IATI Standard links need to start with 'https://iatistandard.org/'? Currently they start with /en ?

Starting with just /en/ will mean these links will work regardless of which domain we host them on. It will work on dev and staging and live. Or if we ever changed the main domain.



> The versions we could do as find and replace for each file?

Yes this'll work. It's universal that if it's a codelist change to 2.01 all links should be to 2.01, etc?

**Pull request merged**
